

server {
    listen           80;
    listen           443 ssl;             # the port nginx is listening on
    server_name      reporter-collector.qullqa.art;    # setup your domain here

    ssl_certificate    /etc/nginx/conf.d/ssl/fullchain.pem;
    ssl_certificate_key    /etc/nginx/conf.d/ssl/privkey.pem;

    gzip             on;
    gzip_types       text/plain application/xml text/css application/javascript;
    gzip_min_length  1000;

    location / {
        proxy_redirect                      off;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_read_timeout 600s;
        proxy_connect_timeout 600s;
        proxy_pass                          http://fastapi:8000; # set the adress of the container
                    }
}